# Generated by Django 3.2.3 on 2021-05-17 09:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210517_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='uploaded_photo/'),
        ),
    ]
